default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0


development:
  <<: *default
  database: shiotter_development

test:
  <<: *default
  database: shiotter_test

production:
  <<: *default
  database: shiotter_production
  username: shiotter
  password: <%= ENV['SHIOTTER_DATABASE_PASSWORD'] %>
